- name : given number is greater than 10 or not
  hosts: local
  connection: local
  vars_prompt:
    Name: My_number
    prompt: Please enter your number here
    private: false
  tasks: 
  - name: given number is greater than 10 
    ansible.builtin.debug:
      msg: "given number {{My_number}} is greater than 10"
    when: My_number | int > 10
  - name: given number is lesser than or equals to 10
    ansible.builtin.debug:
      msg: "given number {{My_number}} is greater than 10"
    when: My_number | int <= 10
  