- name: functions demo
  hosts: web
  tasks:
  - name: print the default value
    ansible.builtin.debug:
      msg: "this is {{NAME | default('Manohar')}}"
  - name: print the default value
    vars:
      NAME: "ManoHAR"
    ansible.builtin.debug:
      msg: "this is {{NAME | upper }}"