- name: command vs shell
  hosts: local
  connection: local
  tasks:
  - name: shell example
    ansible.builtin.shell: ls -ltr > output.txt

  - name: command example
    ansible.builtin.command: ls -ltr
    register: lucky 
  - name: print the op of command
    ansible.builtin.debug:
      msg: "result is {{lucky}}"