- name: installing and running nginx
  hosts: web
  become: yes
  tasks:
  - name: installing nginx
    ansible.builtin.package:
      name: nginx
      state: started
  - name: running nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes